### ISSUE TITLE
Level design

### ISSUE THREAD

**Issue by bencz** [bencz/BCC_PI2_chernobyl#3]
@saulohdc,
Saulo, por favor, envie exemplos ou amostras de algumas fases ou mesmo alguns testes que você fez.
@unphook e @paulomag2106 ,
Sobre a questão que o Saulo comentou, "Ainda estou pensando se deixo a parte de trás como estática ou não.", o que vocês acham ?

**Comment by paulomag2106** [comment]
eu conversei com o saulo ontem à noite, ele tava com uma ideia de
implementar Parallaxing no fundo dos cenários. pelo design do game,
independente de ter scrolling entre uma tela e outra ou não, enquanto o
personagem não sair da tela, ela não se mexe e portanto o efeito não vai
aparecer... do ponto de vista gráfico, na melhor das hipóteses, é um efeito
sutil. MAS... pode ser um desafio interessante em termos de implementação
de código, o professor pode interpretar como um extra na programação.

2015-10-02 9:54 GMT-03:00 Alexandre Bencz notifications@github.com:

**Comment by olmewe** [comment]
é, por conta das telas serem estáticas, o efeito de parallax seria só algo a mais na transição entre uma tela e outra... mas seria legal colocar, sla, tb não é muito difícil de fazer

**Comment by olmewe** [comment]
quanto aos mapas:
largura: 32
altura: 18
todos os mapas terão uma borda, para evitar que o jogador saia dele usando funções.

as camadas do mapa serão, na ordem:
- wires (do tipo camada de objeto): ela indica os circuitos (desenhados com polilinhas) do mapa, que serão alinhados com as bordas das tiles
- collision (do tipo camada de tile): nela, será indicado se há colisão naquela tile ou não. também haverá um tipo de tile indicando se há uma base ali, e bases são indicadas com esse tipo de tile desenhado em 2x2.
- front (do tipo camada de tile): ela contém sprites que não são usados para colisão, mas para serem desenhados na tela. estes serão desenhados na frente do jogador.
- back (do tipo camada de tile): assim como o front, mas estes serão desenhados atrás do jogador.
- parallax (do tipo camada de tile): também serão desenhados atrás do jogador, mas, durante a transição entre dois mapas, ele anda mais lentamente que as outras camadas, dando a ilusão de q as tiles aqui estão mais longes da câmera (efeito de parallax, oras)

tem um exemplo porco na pasta bin/data/levels (q acredito q a altura nele tá errada haha), mas acho q a partir dele dá pra entender como q tão as coisas. dentro dessa mesma pasta ficarão as outras fases, e na pasta bin/data/bitmaps ficam as imagens, então acho q as imagens usadas no tiled também poderiam ficar por lá...
