### ISSUE TITLE
analisador de expressão

### ISSUE THREAD

**Issue by olmewe** [bencz/BCC_PI2_chernobyl#5]
encontrei um problema quanto à precedência de operações, acredito... o input -x^2 é considerado como (-x)², ao invés de -(x²) que imagino que seja o correto.
ah, não esquece de ver algum jeito de interpretar coisas como 2x como 2*x. acho que, se pudesse, também seria legal ele diferenciar 2x (2*x) e x2 (x^2).

**Comment by bencz** [comment]
Para resolver o sistema de colocar 2x e identificar como 2*x, irei implementar um analisador léxico ( isso vai afetar o desempenho, pois terei que fazer toda uma analise da expressão, antes de gerar a expressão final, mas acredito que não seja nada muito agravante!!! ).
Este analisador léxico vai salvar os lexemas ( tokens ) em um array, que já vou deixar com o tamanho pré-definido, para tentar ao máximo aumentar a velocidade do processo, e então vou fazer um loop para ir navegando pela arvore de tokens que vai ser gerada pelo analisador léxico e ir fazendo as devidas correções.

**Comment by bencz** [comment]
Está desenvolvido o sistema de analise léxica, não o coloquei no jogo diretamente, pois não tenho como testar aqui na empresa!! :(
